'''
Created on Jul 10, 2011

How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 
and 2 <= b <= 100?

@author: Admin
'''

comb = set()
limit = 100
for a in range(2, limit+1):
    for b in range(2, limit+1):
        comb.add(a**b)

print len(comb)
# BUG: Cannot print comb without program terminating